### ISSUE TITLE
Copying the CSS value does not always copy to the board

### ISSUE THREAD

**Issue by kingwayne79** [flamencist/CopyCssSelector#2]
Chrome version => Version 75.0.3770.100 (Official Build) (64-bit)
MacOS version => 10.14.5 (Mojave)

Cannot find the reason why but the copy feature does not always copy to the board.  I have even tried to make sure the focus was on the element that I wanted to copy the CSS from by inspecting that element first.  I `Copy CSS Selector` then I go to paste that into my IDE and it pastes the last thing that I copied before copying the CSS.  This happens a lot, and has been happening a lot since I installed the extension about 9 months ago.  It is very frustrating, especially since I cannot figure out why it's doing this.  Let me know what other information you may need

**Added**
One other thing that I forgot to mention and this may actually be relevant, is that this mostly happens when trying to copy CSS from a modal

**Comment by flamencist** [comment]
It's worked on windows and linux for me. I will check on OSX

**Comment by kingwayne79** [comment]
The modal in question is within an access-controlled web page and I cannot give you credentials for, sorry.

**Comment by flamencist** [comment]
I've check on OSX (Mojave). It's worked for me. Is broken on all pages ?

**Comment by flamencist** [comment]
Is not reproduced
